language: go
dist: trusty
go: 1.10.3

before_install:
  - go get -v github.com/aktau/github-release
  - go get -v github.com/golang/dep/cmd/dep

script:
  - make install
  - make build
  - if [[ "$TRAVIS_TAG" != "" ]]; then TAG=${TRAVIS_TAG} make release; fi

notifications:
  email: false
  slack: lnmpy:LSbevEhQZLylhk2zozsnR286
