language: go
dist: trusty
go: 1.10.3
env:
  - PATH=$PATH:$GOPATH/bin

before_install:
  - go get -v github.com/golang/lint/golint
  - go get -v github.com/aktau/github-release

script:
  - make install
  - make build
          
notifications:
  email: false
