language: go
go: 1.12.4
dist: trusty

before_install:
  - go get -v github.com/aktau/github-release

script:
  - make build

after_success:
  - if [[ "$TRAVIS_TAG" != "" ]]; then make release; fi

notifications:
  email: false
  slack: lnmpy:LSbevEhQZLylhk2zozsnR286
