name: Go

on: 
  push:
    branches:
    - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-16.04
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get github-release
      run: go get -v github.com/aktau/github-release
    
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GithubActionsToken }} 
      run: PATH=$(go env GOPATH)/bin:${PATH} make release

